Models/Home.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SoftwareEngineerTest.Models
{
    public class Home
    {
        [Required]
        public string FullName { get; set; }
        [Required]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}")]
        public string Email { get; set; }
        [Required]
        public string phone { get; set; }
        [Required]
        public string address { get; set; }
    }

    public class Items
    {
        public Class1[] Property1 { get; set; }
    }

    public class Class1
    {
        public int ID { get; set; }
        public string Message { get; set; }
        public int Age { get; set; }
    }

}

Controllers/FORMController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using SoftwareEngineerTest.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SoftwareEngineerTest.Controllers
{
    public class FORMController : Controller
    {
        private string result;

        // GET: FORM
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult form()
        {
            return View();
        }
       
        [HttpPost]
        public ActionResult form(Home model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Home home = new Home()
                    {
                        FullName = model.FullName,
                        address = model.address,
                        Email = model.Email,
                        phone = model.phone
                    };
                    string stringjson = JsonConvert.SerializeObject(home);

                    var client = new RestClient("http://developers.gictsystems.com/api/dummy/submit/");
                    client.Timeout = -1;
                    var request = new RestRequest(Method.POST);
                    request.AddHeader("Content-Type", "application/json");
                    var body = stringjson;
                    request.AddParameter("application/json", body, ParameterType.RequestBody);
                    IRestResponse response = client.Execute(request);
                    result = response.Content;
                }
                dynamic json = JObject.Parse(result);
                int statuscode = json.StatusCode;
                string Description = json.Message;

                if (statuscode != 1)
                {
                    TempData["status"] = "success";
                    TempData["Message"] = Description;
                }
                else
                {
                    TempData["status"] = "warning";
                    TempData["Message"] = Description;
                }
            }
            catch (Exception es)
            {
                TempData["Message"] = es;

            }
            return View();
        }

        public ActionResult Table()
        {
            Response.Headers.Add("Refresh", "10");
            var data = Itmes();
            var jsonArray = JArray.Parse(data);

            DataTable dt = new DataTable();
            dt.Columns.Add("ID", typeof(string));
            dt.Columns.Add("Message", typeof(string));
            dt.Columns.Add("Age", typeof(string));
            dt.Columns.Add("ACTION", typeof(string));

            foreach (var item in jsonArray)
            {
                var myJsonObject = Newtonsoft.Json.JsonConvert.DeserializeObject<Models.Class1>(item.ToString());
                dt.Rows.Add(myJsonObject.ID, myJsonObject.Message, myJsonObject.Age, "<a class = 'btn btn-secondary btn-xs' data-toggle='tooltip' title='Edit Application'><span class = 'fa fa-edit'> </span></a> ");

            }
            //Building an HTML string.
            StringBuilder html = new StringBuilder();
            //Table start.
            html.Append("<table class='table table-bordered' id='dataTable' width='100%' cellspacing='0'>");
            //Building the Header row.
            html.Append("<thead>");
            html.Append("<tr>");
            foreach (DataColumn column in dt.Columns)
            {
                html.Append("<th>");
                html.Append(column.ColumnName);
                html.Append("</th>");
            }
            html.Append("</tr>");
            html.Append("</thead>");

            html.Append("<tfoot>");
            html.Append("<tr>");
            foreach (DataColumn column in dt.Columns)
            {
                html.Append("<th>");
                html.Append(column.ColumnName);
                html.Append("</th>");
            }
            html.Append("</tr>");
            html.Append("</tfoot>");

            //Building the Data rows.
            html.Append("<tbody>");
            foreach (DataRow row in dt.Rows)
            {
                html.Append("<tr>");
                foreach (DataColumn column in dt.Columns)
                {
                    html.Append("<td>");
                    html.Append(row[column.ColumnName]);
                    html.Append("</td>");
                }
                html.Append("</tr>");
            }
            html.Append("</tbody>");
            //Table end.
            html.Append("</table>");
            string strText = html.ToString();
            ViewBag.Table = strText;

            return View();
        }

        private static string Itmes()
        {
            var client = new RestClient("http://developers.gictsystems.com/api/dummy/items/");
            client.Timeout = -1;
            var request = new RestRequest(Method.GET);
            request.AddHeader("Content-Type", "application/json");
            request.AddHeader("Authorization", "Bearer ALDJAK23423JKSLAJAF23423J23SAD3");
            IRestResponse response = client.Execute(request);
            var Resp = response.Content;
            return Resp;
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoftwareEngineerTest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/SweetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SweetAlert.Controllers
{
    public class SweetController : Controller
    {
        // GET: Sweet
        public ActionResult Alert()
        {
            return View();
        }
    }
}

Views/FORM/Table.cshtml
@{
    ViewBag.Title = "Table";
}

<main id="main" class="main">
    <div id="wrapper">
        <div id="content-wrapper">
            <div class="container-fluid">
                <div class="card mb-3">
                    <div class="card-header">
                        <div class="card-body">
                            <div class="table-responsive">
                                @Html.Raw(ViewBag.Table)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- Bootstrap core CSS-->
<link href="~/Content/Assest/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- Custom fonts for this template-->
<link href="~/Content/Assest/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
<!-- Page level plugin CSS-->
<link href="~/Content/Assest/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
<link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css" rel="stylesheet">
<script src="~/Content/Assest/vendor/jquery/jquery.min.js"></script>
<script src="~/Content/Assest/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="~/Content/Assest/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="~/Content/Assest/vendor/datatables/jquery.dataTables.js"></script>
<script src="~/Content/Assest/vendor/datatables/dataTables.bootstrap4.js"></script>
<!-- Custom scripts for all pages-->
<script src="~/Content/Assest/js/sb-admin.min.js"></script>
<script src="~/Content/Assest/js/bootbox.all.min.js"></script>
<script src="~/Content/Assest/js/bootboxError.js"></script>
<script src="~/Content/Assest/js/jquery.pleaseWait.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
<script type="text/javascript">var jQuery_3_3_1 = $.noConflict(true);</script>

Views/FORM/form.cshtml
@model SoftwareEngineerTest.Models.Home

@{
    ViewBag.Title = "form";
}


<!-- Vendor CSS Files -->
<link href="~/Content/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="~/Content/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
<link href="~/Content/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
<!-- Template Main CSS File -->
<link href="~/Content/assets/css/style.css" rel="stylesheet">
<main id="main" class="main">
    <div class="container">
        @using (Html.BeginForm(FormMethod.Post))
        {
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

                    <div class="d-flex justify-content-center py-4">

                    </div><!-- End Logo -->

                    <div class="card mb-3">

                        <div class="card-body">
                            <div class="pt-4 pb-2">
                                <h5 class="card-title text-center pb-0 fs-4">Please Fill In The Details</h5>
                            </div>
                            <form class="row g-3 needs-validation" novalidate id="myForm">

                                <div class="col-12">
                                    <label for="yourFullName" class="form-label">Full Name</label>

                                    @Html.TextBoxFor(model => model.FullName, new { @class = "form-control", id = "FullName" })
                                    @Html.ValidationMessageFor(m => m.FullName, "", new { @class = "text-danger" })
                                    <div class="invalid-feedback">Please enter your Email!</div>

                                </div>

                                <div class="col-12">
                                    <label for="yourEmail" class="form-label">Email</label>
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", id = "Email" })
                                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                    <div class="invalid-feedback">Please enter your Email!</div>
                                </div>
                                <div class="col-12">
                                    <label for="yourPhone" class="form-label">Phone</label>
                                    @Html.TextBoxFor(model => model.phone, new { @class = "form-control", id = "phone" })
                                    @Html.ValidationMessageFor(m => m.phone, "", new { @class = "text-danger" })
                                    <div class="invalid-feedback">Please enter your phone!</div>
                                </div>
                                <div class="col-12">
                                    <label for="youraddress" class="form-label">Address</label>
                                    @Html.TextBoxFor(model => model.address, new { @class = "form-control", id = "address" })
                                    @Html.ValidationMessageFor(m => m.address, "", new { @class = "text-danger" })
                                    <div class="invalid-feedback">Please enter your address!</div>
                                </div>
                                @if (TempData["Message"] != null)
                                {
                                    <script type="text/javascript">
                                            window.onload = function () {
                                                swal("", '@TempData["Message"]', '@TempData["status"]');
                                                event.preventDefault();
                                            }
                                    </script>
                                }
                                <div class="col-12">
                                    <br />
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-primary w-100" type="submit" id="btnlogin">Submit</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</main><!-- End #main -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
<script src="~/Content/assets/vendor/apexcharts/apexcharts.min.js"></script>
<script src="~/Content/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/Content/assets/vendor/chart.js/chart.min.js"></script>
<script src="~/Content/assets/vendor/echarts/echarts.min.js"></script>
<script src="~/Content/assets/vendor/quill/quill.min.js"></script>
<script src="~/Content/assets/vendor/simple-datatables/simple-datatables.js"></script>
<script src="~/Content/assets/vendor/tinymce/tinymce.min.js"></script>
<script src="~/Content/assets/vendor/php-email-form/validate.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
<link media="screen" rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.css" />
<link media="screen" rel="stylesheet" href='https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.css' />
<script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.js"></script>
<link href="https://fonts.gstatic.com" rel="preconnect">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title></title>   
    <!-- Favicons -->
    <link href="~/Content/assets/img/favicon.png" rel="icon">
    <link href="~/Content/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- Vendor CSS Files -->
    <link href="~/Content/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/Content/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/Content/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/Content/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/Content/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/Content/assets/vendor/simple-datatables/style.css" rel="stylesheet">
    <!-- Template Main CSS File -->
    <link href="~/Content/assets/css/style.css" rel="stylesheet">
</head>

<body class="bg-dark">
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="#" class="logo d-flex align-items-center">

                <span class="d-none d-lg-block">TEST</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div>
    <!-- End Logo -->
        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="POST" action="#">
                <input type="text" name="query" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div>
    <!-- End Search Bar -->
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->
            </ul>
        </nav><!-- End Icons Navigation -->
    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-item">
                <a class="nav-link " href="#">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#components-nav" role="button" data-bs-toggle="collapse" href="#">
                    <i class="fas fa-fw fa-suitcase"></i><span>FORM</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <a class="dropdown-item" href="@Url.Action("form", "FORM" )">Form</a>                   
                </ul>
            <li>
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#forms-nav" role="button" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-journal-text"></i><span>TABLE</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                    <a class="dropdown-item" href="@Url.Action("Table","FORM")">
                       Table</a>                   
                </ul>
            </li>     
        </ul>
    </aside><!-- End Sidebar-->
    <!-- Vendor JS Files -->
    <script src="~/Content/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/Content/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/assets/vendor/chart.js/chart.min.js"></script>
    <script src="~/Content/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/Content/assets/vendor/quill/quill.min.js"></script>
    <script src="~/Content/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/Content/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/Content/assets/vendor/php-email-form/validate.js"></script>
    <!-- Template Main JS File -->
    <script src="~/Content/assets/js/main.js"></script>
    <script src="~/Assest/vendor/jquery/jquery.min.js"></script>
    <script src="~/Assest/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <link href="~/Assest/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    @*Custom fonts for this template*@
    <link href="~/Assest/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    @*Page level plugin CSS*@
    <link href="~/Assest/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css" rel="stylesheet">
    @*Custom styles for this template*@

    <link href="~/Assest/css/custom.css" rel="stylesheet">
    @*Core plugin JavaScript*@
    <script src="~/Assest/vendor/jquery-easing/jquery.easing.min.js"></script>

    @*Page level plugin JavaScript*@
    <script src="~/Assest/vendor/datatables/jquery.dataTables.js"></script>
    <script src="~/Assest/vendor/datatables/dataTables.bootstrap4.js"></script>

    @*Custom scripts for all pages*@
    <script src="~/Assest/js/sb-admin.min.js"></script>
    <script src="~/Assest/js/bootbox.all.min.js"></script>
    <script src="~/Assest/js/bootboxError.js"></script>
    <script src="~/Assest/js/jquery.pleaseWait.js"></script>

    @*Demo scripts for this page*@
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
 
    @RenderBody()
</body>

</html>